services:
  # Backend Development Service
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: sentiment-analyzer-backend
    environment:
      NODE_ENV: development
      PORT: 3056
      HOST: 0.0.0.0
      DATABASE_URL: file:./dev.db
    ports:
      - "3056:3056"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_data:/app/prisma

  # Frontend Development Service
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: sentiment-analyzer-frontend
    environment:
      NODE_ENV: development
      API_ENDPOINT_SERVER: http://backend:3056/api
      API_ENDPOINT_CLIENT: http://localhost:3056/api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

volumes:
  backend_data:
